name: validate_index
on:
  pull_request:
    branches:
      - main
jobs:
  run-validate-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r requirements.txt
      - run: python make_index.py validate